### ISSUE TITLE
F0修改建议

### ISSUE THREAD

**Issue by pujiaxun** [Crecendow/web_tasks#1]
- 要求是一个登陆页面，为什么会有确认密码输入框...
- 记住密码应该用`checkbox`，而不是两个`radio`
- 不建议用`table`来实现布局，这种场景建议使用div+css
- 看清任务要求，是在F0下放置一个`README.md`而不是`readme.txt`

**检查项未完成，请认真阅读任务要求，做出修改**

**Comment by Crecendow** [comment]
我觉得用radio是操作习惯的问题，默认不记住，想要记住密码就点，不会不方便

**Comment by pujiaxun** [comment]
不是。。你见过哪个网站 记住密码是两个单选框，记住点左边，不记住点右边...
通常不都是一个复选框可以打钩的那种吗？

https://coding.net/login
https://www.baidu.com/
http://weibo.com/ 
随便找几个网站你看看他们登陆界面

**Comment by pujiaxun** [comment]
像下面这样的表示你远端有提前本地的提交，而且还冲突了，你应该解决掉再提交。你检查看看你现在的代码，和github上的代码。
查一下如何解决git conflict

```
<<<<<<<HEAD
>>>>>>>>>something
```

``` html
<<<<<<< HEAD
             <tr><th><input type="submit" value="登录"> <input type="submit" value="注册"></th></tr>
                     <tr><th>记住我<input type="checkbox" name="choice" value="remember" checked="checked"/>   <a href="#">无法登录</a></th></tr>
=======

             <tr><th>记住我<input type="checkbox" name="choice" value="remember" />    不记住</th></tr>
             <tr><th><input type="submit" value="登录"> <input type="submit" value="注册"></th></tr>

>>>>>>> b68530734bab8bac6b38677192751695885d8a52
```
